from typing import Dict, Optional, List
import re


def _extract_files_from_patch(patch_markdown: str) -> List[str]:
    """Extracts file names from the patch for a short PR summary."""
    files = set()

    for line in patch_markdown.splitlines():
        line = line.strip()

        # 1) Headers like: "### controller.py"
        if line.startswith("### "):
            name = line[4:].strip()
            if "." in name and " " not in name:
                files.add(name)

        # 2) Lines like: "FILE: path/to/file.py"
        if line.startswith("FILE: "):
            name = re.sub(r"\s*\(line.*\)$", "", line[6:].strip())
            if name:
                files.add(name)

        # 3) Bolded filenames: "* **controller.py**", "- **agent/cli.py**"
        bold_match = re.search(r"\*\*(?P<name>[^*]+?\.[a-zA-Z0-9_]+)\*\*", line)
        if bold_match:
            name = bold_match.group("name").strip()
            files.add(name)

    return list(files)


def generate_pr_payload(
    question: str,
    patch_markdown: str,
    critic: Dict,
    repo_hint: Optional[str] = None,
) -> Dict[str, str]:

    files = _extract_files_from_patch(patch_markdown)
    files_md = "\n".join(f"- `{f}`" for f in files) if files else "- (no files detected)"

    title = f"Repo Copilot: suggestions for '{question[:60]}...'"
    body_lines = []

    if repo_hint:
        body_lines.append(f"Repository: `{repo_hint}`\n")

    body_lines.append("## Summary")
    body_lines.append(f"- Request: `{question}`")
    body_lines.append("- Suggested updates to the following files:")
    body_lines.append(files_md)
    body_lines.append("")
    body_lines.append("## Notes")
    body_lines.append(
        "This is a dry-run suggestion generated by Repo Copilot. "
        "Please review and apply manually if appropriate."
    )
    body_lines.append("")
    body_lines.append("> Generated by Repo Copilot – Ciklum AI Academy")

    return {
        "title": title,
        "body": "\n".join(body_lines),
    }